### ISSUE TITLE
The package '@dongminyu/react-native-step-counter' doesn't seem to be linked

### ISSUE THREAD

**Issue by bundittha** [AndrewDongminYoo/react-native-step-counter#29]
# React Native Step Counter New Issue

System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M2 Pro
  Memory: 90.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.19.1
    path: /var/folders/9b/n0rg4df53tl1jtslh236tfmm0000gn/T/yarn--1692443137067-0.6712097544769973/node
  Yarn:
    version: 1.22.19
    path: /var/folders/9b/n0rg4df53tl1jtslh236tfmm0000gn/T/yarn--1692443137067-0.6712097544769973/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v16.19.1/bin/npm
  Watchman:
    version: 2023.04.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/buddy/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "33"
    Build Tools:
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
    System Images:
      - android-29 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/buddy/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Expected Behavior

- I am trying to build with this library.

## Actual Behavior

- I am getting the following error only on Android when newArchEnabled = false 
- On Android newArchEnabled = true it work normally

![Screenshot_20230819_181029](https://github.com/AndrewDongminYoo/react-native-step-counter/assets/126144938/419157a5-5e1f-43a3-96d1-fc9cde361ea7)

- I think it relate to this line. I have log NativeModule.RNStepCounter is null
<img width="945" alt="Screenshot 2566-08-19 at 18 12 51" src="https://github.com/AndrewDongminYoo/react-native-step-counter/assets/126144938/93e4a0ef-87b6-40db-bb49-3414cfc94e5e">

## Specifications
- @dongminyu/react-native-step-counter version: 0.1.14

**Comment by bundittha** [comment]
I have an update 
As I try when I

**Comment by bundittha** [comment]
<img width="605" alt="Screenshot 2566-08-25 at 00 36 16" src="https://github.com/AndrewDongminYoo/react-native-step-counter/assets/126144938/9a9713f7-b83e-4c25-b367-76164fbe78c5">
I think this is root cause, I can fixed by patch-package. Thank you for your times @AndrewDongminYoo

**Comment by zvici** [comment]
<img width="407" alt="image" src="https://github.com/AndrewDongminYoo/react-native-step-counter/assets/50741034/f04234dd-2a1a-4f1e-bc5d-409c1bdaa168">

"@dongminyu/react-native-step-counter": "^0.2.1"
"react-native": "0.70.6"

in gradle.properties 
newArchEnabled=false

I also have the same problem

**Comment by fzerman** [comment]
I have same error with 0.2.1 on react-native 0.71.11

**Comment by AndrewDongminYoo** [comment]
Well 🧐🧐🧐 I apologize for the delayed update on the issue. It looks like the syntax for `NativeModules.RNStepCounter` should be changed to `NativeModules.StepCounter`, as you're pointing out. I'll try to get that into the code as soon as possible. Please use tools like patch-packages to prioritize this. Thanks for being patient.

**Comment by morricedev** [comment]
same problem here, it looks like the package is not linking automatically on android
ios is working fine

**Comment by mehandi-bytes** [comment]
same problem here, it looks like the package is not linking please help me out

**Comment by morricedev** [comment]
@mehandi-bytes 

Which release are you trying? The v0.2.2 is working for me.

**Comment by bundittha** [comment]
> **0.2.3**
> ### can you please provide me a step for installation

If you facing same problem with me I think problem is this class

<img width="928" alt="Screenshot 2566-10-18 at 17 38 56" src="https://github.com/AndrewDongminYoo/react-native-step-counter/assets/126144938/08032f46-ce1a-430f-9ebc-0b8eced9c7e0">

you can extend with this class  **_ReactContextBaseJavaModule(context)_**
Hope it can help

**Comment by mehandi-bytes** [comment]
![image](https://github.com/AndrewDongminYoo/react-native-step-counter/assets/142971776/01c63538-ca10-4830-89ab-2d1c6b9ff2c4)

**Comment by mehandi-bytes** [comment]
instead i got this error

![image](https://github.com/AndrewDongminYoo/react-native-step-counter/assets/142971776/e538c31a-a488-4174-8843-cc6eade31b0f)

**Comment by bundittha** [comment]
> instead i got this error
> 
> ![image](https://user-images.githubusercontent.com/142971776/276224513-e538c31a-a488-4174-8843-cc6eade31b0f.png)
My solution will work only in old architecture I see you turn on new architecture. I did't face issue on new architect

**Comment by morricedev** [comment]
@mehandi-bytes Could you downgrade to 0.2.2 version and try again?

It may be that some change in this new version is causing this error

**Comment by mehandi-bytes** [comment]
> @mehandi-bytes Could you downgrade to 0.2.2 version and try again?
> 
> It may be that some change in this new version is causing this error

i have done it to low version as a result not working

**Comment by morricedev** [comment]
> > @mehandi-bytes Could you downgrade to 0.2.2 version and try again?
> > It may be that some change in this new version is causing this error
> 
> i have done it to low version as a result not working

I recommend you open a new issue with more details, so I can help you better there
