### ISSUE TITLE
Unable to resolve dependencies with React Native 0.73.2

### ISSUE THREAD

**Issue by francisli** [AndrewDongminYoo/react-native-step-counter#38]
# React Native Step Counter New Issue

## Expected Behavior

- I should be able add this library to a React Native 0.73.2 project

## Actual Behavior

- I am getting the following error:

```log
% npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: intentional-walk-client@2.2.1
npm ERR! Found: react-native@0.73.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.73.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.71.0 || ^0.72.0" from @dongminyu/react-native-step-counter@0.2.4
npm ERR! node_modules/@dongminyu/react-native-step-counter
npm ERR!   @dongminyu/react-native-step-counter@"^0.2.4" from the root project
```

**Comment by AndrewDongminYoo** [comment]
Thanks for the first issue report. It was a misunderstanding on my part about peer dependency, which was relying on a specific React native version. This has been removed in [commit](https://github.com/AndrewDongminYoo/react-native-step-counter/commit/b3e7191dca62b6ba7b68fd7f39a2a18d30b004a6), which you can find in version [0.2.5](https://github.com/AndrewDongminYoo/react-native-step-counter/releases/tag/v0.2.5) released today.
