### ISSUE TITLE
Type mismatch: inferred type is Sensor? but Sensor was expected

### ISSUE THREAD

**Issue by Ugur-Atakan** [AndrewDongminYoo/react-native-step-counter#40]
# React Native Step Counter New Issue

## Expected Behavior

- I am trying to build with this library.

## Actual Behavior

- I am getting the following error:

```
> Task :dongminyu_react-native-step-counter:compileDebugKotlin FAILED
e: file:///C:/Users/uguratakan/Desktop/Projects/BlokField/blokfield/node_modules/@dongminyu/react-native-step-counter/android/src/main/java/com/stepcounter/services/AccelerometerService.kt:46:43 Type mismatch: inferred type is Sensor? but Sensor was expected
e: file:///C:/Users/uguratakan/Desktop/Projects/BlokField/blokfield/node_modules/@dongminyu/react-native-step-counter/android/src/main/java/com/stepcounter/services/StepCounterService.kt:40:43 Type mismatch: inferred type is Sensor? but Sensor was expected

```

## Steps to Reproduce the Problem

1. `yarn create react-native-app my-app`
2. `yarn add @dongminyu/react-native-step-counter`
5. `npx react-native run-*android*`

## Specifications

- @dongminyu/react-native-step-counter version: all

**Comment by dkel3slek** [comment]
같은 현상이 있습니다.

**Comment by dkel3slek** [comment]
Thank you for your kind reply.

**Comment by AndrewDongminYoo** [comment]
@Ugur-Atakan I really appreciate the interest and participation you've shown in this package. I know it's late, but I've seen the issue. could you please send me a pull request from your [fork](https://github.com/Ugur-Atakan/react-native-step-counter-fixed) if you don't mind?

**Comment by AndrewDongminYoo** [comment]
Is fixing by [#42](https://github.com/AndrewDongminYoo/react-native-step-counter/pull/43)
