### ISSUE TITLE
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'StepCounter' could not be found. 

### ISSUE THREAD

**Issue by reneumeh** [AndrewDongminYoo/react-native-step-counter#44]
# React Native Step Counter New Issue
Operating System: Windows

Using: Expo@49.0.23
           react-native@0.72.10

System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 2.03 GB / 15.86 GB
Binaries:
  Node:
    version: 18.12.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34622.214 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## Expected Behavior

- I am trying to build with this library (version==0.2.4)

## Actual Behavior

- I am getting the following error:
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'StepCounter' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

## Steps to Reproduce the Problem

**
npm install expo-cli --global
npx create-expo-app . --template blank-typescript@sdk-49
npm install expo-sensors@12.3.0
npm install --global @expo/ngrok@^4.1.0     
npx expo install react-dom react-native-web @expo/metro-runtime   
npx expo install @expo/webpack-config@^18.0.1                                                                             
npm install @dongminyu/react-native-step-counter
npm start -- --tunnel
**

OR

1. `npm install @dongminyu/react-native-step-counter`
2. `npm start -- --tunnel`

**Comment by AndrewDongminYoo** [comment]
First of all, thank you for reporting your first issue. Based on your issue description, it sounds like you want to use this library for your Expo application, but it's my understanding that this library is implemented in Turbomodule, one of React Native's newer architectures, so it's not available in Expo Go. We've set up an error message to inform you of this, but it doesn't seem to have gotten through to you. There is a library in the expo faction called expo-sensors that should be able to fully implement the functionality you're looking to implement in this library. I'll close this issue with a simple example.

```javascriptreact
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Pedometer } from 'expo-sensors';

export default function App() {
  const [currentStepCount, setCurrentStepCount] = useState(0);

  useEffect(() => {
    const subscription = Pedometer.watchStepCount(result => {
      setCurrentStepCount(result.steps);
    });

    return () => subscription.remove();
  }, []);

  return (
    <View style={styles.container}>
      <Text>Steps taken: {currentStepCount}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
});
```

[See More](https://docs.expo.dev/versions/latest/sdk/pedometer/#usage)

**Comment by MaxiAschenbrenner** [comment]
@AndrewDongminYoo Im having the same Problem using RN v74.3 without Expo. 
(NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'StepCounter' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: true. TurboModule interop: true
Any idea on how to fix this?
